// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RBHU_DbServices.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public decimal OfferPrice { get; set; }

    public string ImageUrl { get; set; }

    public int CategoryId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? SubCategory1_Id { get; set; }

    public int? SubCategory2_Id { get; set; }

    public virtual Category Category { get; set; }

    public virtual SubCategory1 SubCategory1 { get; set; }

    public virtual SubCategory2 SubCategory2 { get; set; }
}