// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RBHU_DbServices.Models;

public partial class RBHUContext : DbContext
{
    public RBHUContext(DbContextOptions<RBHUContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Email> Emails { get; set; }

    public virtual DbSet<EmailAttachment> EmailAttachments { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<SubCategory1> SubCategory1s { get; set; }

    public virtual DbSet<SubCategory2> SubCategory2s { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Category__3214EC07F507BDA7");

            entity.ToTable("Category");

            entity.HasIndex(e => e.Name, "UQ__Category__737584F6BF245890").IsUnique();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Email>(entity =>
        {
            entity.HasIndex(e => new { e.IsContactForm, e.ReceivedUtc }, "IX_Emails_Composite_ContactForm_Received").IsDescending(false, true);

            entity.HasIndex(e => e.FromEmail, "IX_Emails_FromEmail");

            entity.HasIndex(e => e.GmailUid, "IX_Emails_GmailUid");

            entity.HasIndex(e => e.IsContactForm, "IX_Emails_IsContactForm");

            entity.HasIndex(e => e.ReceivedUtc, "IX_Emails_ReceivedUtc").IsDescending();

            entity.HasIndex(e => e.UniqueEmailId, "IX_Emails_UniqueEmailId").IsUnique();

            entity.Property(e => e.Company).HasMaxLength(500);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Folder)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("INBOX");
            entity.Property(e => e.FromEmail)
                .IsRequired()
                .HasMaxLength(500)
                .HasDefaultValue("");
            entity.Property(e => e.FromName)
                .IsRequired()
                .HasMaxLength(500)
                .HasDefaultValue("");
            entity.Property(e => e.GstNumber).HasMaxLength(50);
            entity.Property(e => e.LabelsJson).HasMaxLength(2000);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.ReceivedLocal)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("");
            entity.Property(e => e.Snippet)
                .IsRequired()
                .HasMaxLength(500)
                .HasDefaultValue("");
            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(1000)
                .HasDefaultValue("");
            entity.Property(e => e.UniqueEmailId)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getutcdate())");
        });

        modelBuilder.Entity<EmailAttachment>(entity =>
        {
            entity.HasIndex(e => e.EmailId, "IX_EmailAttachments_EmailId");

            entity.Property(e => e.AttachmentId)
                .IsRequired()
                .HasMaxLength(500)
                .HasDefaultValue("");
            entity.Property(e => e.ContentType).HasMaxLength(200);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(500)
                .HasDefaultValue("");

            entity.HasOne(d => d.Email).WithMany(p => p.EmailAttachments).HasForeignKey(d => d.EmailId);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Product__3214EC079C2C95C6");

            entity.ToTable("Product");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasColumnType("ntext");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.OfferPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Product__Categor__534D60F1");

            entity.HasOne(d => d.SubCategory1).WithMany(p => p.Products)
                .HasForeignKey(d => d.SubCategory1_Id)
                .HasConstraintName("FK_Product_SubCategory1");

            entity.HasOne(d => d.SubCategory2).WithMany(p => p.Products)
                .HasForeignKey(d => d.SubCategory2_Id)
                .HasConstraintName("FK_Product_SubCategory2");
        });

        modelBuilder.Entity<SubCategory1>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SubCateg__3214EC07E10DABCD");

            entity.ToTable("SubCategory1");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Category).WithMany(p => p.SubCategory1s)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_SubCategory1_Category");
        });

        modelBuilder.Entity<SubCategory2>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SubCateg__3214EC07E787DC8E");

            entity.ToTable("SubCategory2");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.SubCategory1).WithMany(p => p.SubCategory2s)
                .HasForeignKey(d => d.SubCategory1Id)
                .HasConstraintName("FK_SubCategory2_SubCategory1");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}