// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RBHU_DbServices.Models;

public partial class SubCategory1
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? CategoryId { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<SubCategory2> SubCategory2s { get; set; } = new List<SubCategory2>();
}