// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RBHU_DbServices.Models;

public partial class SubCategory2
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? SubCategory1Id { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual SubCategory1 SubCategory1 { get; set; }
}